title: Your awesome title
author: Erynvorn
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is my new test blog
  It is going to be awesome
  Absolutely Fabulous

# social links
twitter_username: your-twitter-handle
github_username:  Erynvorn

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minima
